### PR TITLE
PLANET-5493 Fix articles block manual override JS test

### PR DESCRIPTION
**Pull request by sagarsdeshmukh**
Related to [JIRA #5493](https://jira.greenpeace.org/browse/PLANET-5493)

### CODE REVIEW

**Review by lithrel — APPROVED** [review]
:+1: 
(php 7.2 test failed for some unrelated http response failure :man_shrugging: should pass on next run)

**Comment by sagarsdeshmukh** [comment]
> 👍
> (php 7.2 test failed for some unrelated http response failure 🤷‍♂️ should pass on next run)

Hi @lithrel , Thanks for the review :) , I update the PR after your last review. Earlier the test was depends on default content post data, now we create required posts(needed to test manual override ) within test execution.
cc: @Inwerpsel

**Comment by lithrel** [comment]
Still good to me :+1: 
Side question, because article titles inserted are not very specific, if other tests run in the same instance and create a post with similar title, will it mess up the test ? If it's the case I would prefix the title with the test name or something recognizable.

**Comment by sagarsdeshmukh** [comment]
> Still good to me 👍
> Side question, because article titles inserted are not very specific, if other tests run in the same instance and create a post with similar title, will it mess up the test ? If it's the case I would prefix the title with the test name or something recognizable.

The post/page with same name will not affect on test result, but its a good suggestion to keep test name in post title. 👍

**Pull request merged**
