### PR TITLE
Update Browserslist DB

### PR DESCRIPTION
**Pull request by lithrel**
Update Browserslist DB

Cf. https://github.com/browserslist/update-db#readme

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [leda](https://www-dev.greenpeace.org/test-leda) | [admin](https://www-dev.greenpeace.org/test-leda/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-leda/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-leda) | [composer-local.json](https://github.com/greenpeace/planet4-test-leda/blob/main/composer-local.json)

:watch: 2023.07.21 07:54:26

**Comment by mleray** [comment]
Weird that the frontend tests are failing, seems unrelated 🤔

**Comment by lithrel** [comment]
> Weird that the frontend tests are failing, seems unrelated thinking

@mleray fixed by https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1094 :pray:

**Review by mleray — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
