### PR TITLE
PLANET-4382: Can't edit/add items of Carousel header

### PR DESCRIPTION
**Pull request by pablocubico**
Ref: https://jira.greenpeace.org/browse/PLANET-4382

The fixes were:
- add Carousel Header styles to the editor styles
- prevent the carousel_header script to add the indicators twice
- adjust the click area of the slides accordion and polish the styles

### CODE REVIEW

**Comment by sagarsdeshmukh** [comment]
Hi @pablocubico - I am getting below error on adding of carousal header in page. (I am checking it on my [dev instance](https://k8s.p4.greenpeace.org/sagardev/) by pining the G-block branch to `planet-4382`)
https://k8s.p4.greenpeace.org/sagardev/wp-admin/post.php?post=915&action=edit
image

**Comment by pablocubico** [comment]
Hmmm thanks @sagarsdeshmukh I'll check!

**Comment by comzeradd** [comment]
@pablocubico can you rebase?

**Comment by pablocubico** [comment]
@sagarsdeshmukh @comzeradd updated and rebased, I had to cherry-pick the commits because there was an extra one around, probably from a rebase mistake.

**Comment by pablocubico** [comment]
@dpivo Logs removed! I couldn't reproduce the focus point issue. I guess we can create a separate ticket for it.

**Comment by dpivo** [comment]
> @dpivo Logs removed! I couldn't reproduce the focus point issue. I guess we can create a separate ticket for it.

I'ts all good now. Maybe it was an error on my side 👍

**Pull request merged**
