### PR TITLE
PLANET-7189 Remove our uses of ReactDOM.render

### PR DESCRIPTION
**Pull request by Osong-Michael**
**Description: [PLANET-7189](https://jira.greenpeace.org/browse/PLANET-7189)**

**Testing:**

Nothing should change visually, only upgraded imports to match React 18 [recommendations](https://react.dev/blog/2022/03/08/react-18-upgrade-guide).

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [jupiter](https://www-dev.greenpeace.org/test-jupiter) | [admin](https://www-dev.greenpeace.org/test-jupiter/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-jupiter/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-jupiter) | [composer-local.json](https://github.com/greenpeace/planet4-test-jupiter/blob/main/composer-local.json)

:watch: 2023.07.28 10:33:55

**Review by mleray — APPROVED** [review]
Looks good to me, seems everything still works fine 👍

**Comment by mleray** [comment]
I now get some new errors on pages with a Gallery block, e.g. 

```
Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
```
and 
```
Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
```

**Comment by Osong-Michael** [comment]
> I now get some new errors on pages with a Gallery block, e.g.
> 
> ```
> Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
> ```
> 
> and
> 
> ```
> Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
> ```



> jupiter



> I now get some new errors on local on pages with a Gallery block, e.g.
> 
> ```
> Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
> ```
> 
> and
> 
> ```
> Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
> ```

Hey @mleray, is it the homepage on the local, and by any chance are there some images that don't display on the Frontend?

**Comment by mleray** [comment]
> Hey @mleray, is it the homepage on the local, and by any chance are there some images that don't display on the Frontend?

It was not on the homepage, it was on the [Energy page](http://www.planet4.test/explore/energy/)... But indeed some images are missing

**Comment by Osong-Michael** [comment]
> admin

Yea, it is a weird situation, the workaround will be to edit those pages and update the images, as for now I couldn't find a way to resolve that as React is only concerned with making sure the UI from the server and client match

**Comment by Osong-Michael** [comment]
> > Hey @mleray, is it the homepage on the local, and by any chance are there some images that don't display on the Frontend?
> 
> It was not on the homepage, it was on the [Energy page](http://www.planet4.test/explore/energy/)... But indeed some images are missing


Yea, it is a weird situation, the workaround will be to edit those pages and update the images, as for now I couldn't find a way to resolve that as React is only concerned with making sure the UI from the server and client match

**Review by mleray — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
