### PR TITLE
 PLANET-7611: Use the block name "Happy Point" consistently

### PR DESCRIPTION
**Pull request by mardelnet**
Ref: https://jira.greenpeace.org/browse/PLANET-7611

<hr>

**DESCRIPTION:**
As different names for the "Happypoint" block are used in our code (in some parts, we call it "Happypoint", in others, "happy point", "Happy Point", etc.), this PR replaces them all with the string "Happy Point", to keep it consistent.

<hr>

**RELATED PR:**
https://github.com/greenpeace/planet4-master-theme/pull/2377

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [pandora](https://www-dev.greenpeace.org/test-pandora) | [admin](https://www-dev.greenpeace.org/test-pandora/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-pandora/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pandora) | [composer-local.json](https://github.com/greenpeace/planet4-test-pandora/blob/main/composer-local.json)

:watch: 2024.09.12 08:00:23

**Comment by mleray** [comment]
@mardelnet as we discussed on Slack, it would be better to just fully remove this block from the plugin instead of making these changes in two places!

**Comment by mardelnet** [comment]
> @mardelnet as we discussed on Slack, it would be better to just fully remove this block from the plugin instead of making these changes in two places!

You're right @mleray:
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1246

**Comment by mardelnet** [comment]
Closing this PR in favor of https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1246

**Pull request closed without merging**
