### PR TITLE
PLANET-4520: Split and clean up js dependencies 

### PR DESCRIPTION
**Pull request by pablocubico**
Ref: https://jira.greenpeace.org/browse/PLANET-4520

This could be tested by deleting the node_modules folder, running npm install again and making sure everything works.

### CODE REVIEW

**Comment by pablocubico** [comment]
@Inwerpsel arggh, sorry, I was just making a few updates to this, can you check again? thanks!

**Comment by pablocubico** [comment]
This is the output of `npx depcheck` for this repo:

```
npx: installed 72 in 6.824s
Unused devDependencies
* bootstrap
* node-sass
Missing dependencies
* @wordpress/element: ./assets/src/components/EmptyMessage/EmptyMessage.js
* @wordpress/i18n: ./assets/src/components/AssignOnlyFlatTermSelector/AssignOnlyFlatTermSelector.js
* @wordpress/compose: ./assets/src/components/AssignOnlyFlatTermSelector/AssignOnlyFlatTermSelector.js
* @wordpress/api-fetch: ./assets/src/components/AssignOnlyFlatTermSelector/AssignOnlyFlatTermSelector.js
* @wordpress/url: ./assets/src/components/AssignOnlyFlatTermSelector/AssignOnlyFlatTermSelector.js
* @wordpress/editor: ./assets/src/components/ImageOrButton/ImageOrButton.js
* @wordpress/block-editor: ./assets/src/blocks/Carouselheader/CarouselHeaderSlide.js
```

Despite it's listing some missing dependencies, the build works, and we actually need `bootstrap` and `node-sass`, which are listed as unused. Not sure what's going on under the hood, maybe those `@wordpress/...` dependencies are already part of `@wordpress/scripts` or `@wordpress/components` or `@wordpress/data`...

**Comment by Inwerpsel** [comment]
> This is the output of `npx depcheck` for this repo:
> 
> ```
> npx: installed 72 in 6.824s
> Unused devDependencies
> * bootstrap
> * node-sass
> Missing dependencies
> * @wordpress/element: ./assets/src/components/EmptyMessage/EmptyMessage.js
> * @wordpress/i18n: ./assets/src/components/AssignOnlyFlatTermSelector/AssignOnlyFlatTermSelector.js
> * @wordpress/compose: ./assets/src/components/AssignOnlyFlatTermSelector/AssignOnlyFlatTermSelector.js
> * @wordpress/api-fetch: ./assets/src/components/AssignOnlyFlatTermSelector/AssignOnlyFlatTermSelector.js
> * @wordpress/url: ./assets/src/components/AssignOnlyFlatTermSelector/AssignOnlyFlatTermSelector.js
> * @wordpress/editor: ./assets/src/components/ImageOrButton/ImageOrButton.js
> * @wordpress/block-editor: ./assets/src/blocks/Carouselheader/CarouselHeaderSlide.js
> ```
> 
> Despite it's listing some missing dependencies, the build works, and we actually need `bootstrap` and `node-sass`, which are listed as unused. Not sure what's going on under the hood, maybe those `@wordpress/...` dependencies are already part of `@wordpress/scripts` or `@wordpress/components` or `@wordpress/data`...
> 
> cc @Inwerpsel @comzeradd

This could be because wordpress does something special for `@wordpress/*` dependencies. I don't remember exactly how it does it, but it comes down to wordpress avoiding to install packages as they are already availble in the global `wp` variable, so those are used instead.

**Comment by comzeradd** [comment]
I'd suggest to rebase and merge it against the develop branch, so we have more time to test it

**Comment by pablocubico** [comment]
@comzeradd rebased.

**Pull request merged**
