### PR TITLE
add bullets in jsx with aria-hidden to article preview

### PR DESCRIPTION
**Pull request by DanceParty**
Ref: 2/2 of https://github.com/greenpeace/planet4/issues/114

Sibling PR: https://github.com/greenpeace/planet4-master-theme/pull/1367

## Description

1. Add the bullets into the ArticlePreview component so that we can hide them from the screenreader (tested on MacOS VoiceOver) ✅

2. Hide the `#` that appears in the ArticlePreview component from the screenreader ⁉️
    - I wanted to push back on this one a little bit. It seems that we are already marking this symbol with the `aria-label="hashtag"` which seems appropriate for the screenreader to read. Not totally against removing it, but wanted to double check that we really _do_ want to remove it first.
    
## Potential Issues

None that I can see

## Screenshot

Screen Shot 2021-04-15 at 5 18 09 PM

---

### CODE REVIEW

**Comment by DanceParty** [comment]
@comzeradd Hey, wondering if there is anything I can fix on my side to address the CI issue:

`Exception: No corresponding issue found, booking will not be executed.`

**Comment by Inwerpsel** [comment]
> @comzeradd Hey, wondering if there is anything I can fix on my side to address the CI issue:
> 
> `Exception: No corresponding issue found, booking will not be executed.`

@DanceParty It's not a problem, the job is expected to fail except for team members. It deploys the commit to a test instance so it requires some secret environment variables. @comzeradd Perhaps we can set up the job in a way that it doesn't show up as failed?

**Comment by comzeradd** [comment]
> @comzeradd Perhaps we can set up the job in a way that it doesn't show up as failed?

Could also post a comment back here when it's successful :grin:

**Comment by lithrel** [comment]
Thanks @DanceParty, looking good, just a detail on conditions of bullet appearance; we can have a page type and no tags, and with current modifications this make a bullet appear all alone:
Screenshot from 2021-04-27 09-22-14

I think you could apply a condition for the bullet, something like this for example (my js is not fantastic, please feel free to make it better :grin: )
```diff
diff --git a/assets/src/blocks/Articles/ArticlePreview.js b/assets/src/blocks/Articles/ArticlePreview.js
index 604f4ee..3784f16 100644
--- a/assets/src/blocks/Articles/ArticlePreview.js
+++ b/assets/src/blocks/Articles/ArticlePreview.js
@@ -49,7 +49,6 @@ export class ArticlePreview extends Component {
               <a href={authorLink}>{authorName}</a>
             }
           </span>
-          <span className="article-list-item-bullet" aria-hidden="true">&#8226;</span>
         </>
       );
     }
@@ -110,6 +109,8 @@ export class ArticlePreview extends Component {
     } = this.props;
 
     const articleClassName = tags.reduce((classname, tag) => classname + ` tag-${tag.slug}`, 'article-list-item');
+    const authorLink = this.getAuthorLink();
+
 
     return (
       <article className={articleClassName} >
@@ -121,7 +122,9 @@ export class ArticlePreview extends Component {
                 this.getPageTypesTags(page_type, page_type_link)
               }
 
-              <span className="tag-wrap-bullet" aria-hidden="true">&#8226;</span>
+              {page_type && tags.length > 0 &&
+                <span className="tag-wrap-bullet" aria-hidden="true">&#8226;</span>
+              }
 
               {tags.length > 0 &&
                 <div className="tag-wrap tags">
@@ -155,7 +158,10 @@ export class ArticlePreview extends Component {
               </h4>
             }
             <p className="article-list-item-meta">
-              {this.getAuthorLink()}
+              {authorLink}
+              {authorLink && date_formatted &&
+                <span className="article-list-item-bullet" aria-hidden="true">&#8226;</span>
+              }
               {date_formatted &&
               <time className="article-list-item-date" dateTime="">
                 {date_formatted}
```

**Pull request merged**
