### PR TITLE
PLANET-5424 Spreadsheet block: URL vanishes after page being published

### PR DESCRIPTION
**Pull request by dpivo**
set url value to attributes.url as opposed to state.url

### CODE REVIEW

**Review by mleray — CHANGES_REQUESTED** [review]
This will cause a delay when typing in the input, since the attributes' url is updated with a [debounce function](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Spreadsheet/SpreadsheetEditor.js#L51) A solution would be to initialise `this.state.url` to `attributes.url` instead of the current `''` ([here](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Spreadsheet/SpreadsheetEditor.js#L48))

**Comment by dpivo** [comment]
> This will cause a delay when typing in the input, since the attributes' url is updated with a [debounce function](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Spreadsheet/SpreadsheetEditor.js#L51) A solution would be to initialise `this.state.url` to `attributes.url` instead of the current `''` ([here](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Spreadsheet/SpreadsheetEditor.js#L48))

I don't think the attributes object is visible at that point. So I set it on renderEdit(). Let me know if it's ok :ok_hand:

**Comment by mleray** [comment]
> > This will cause a delay when typing in the input, since the attributes' url is updated with a [debounce function](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Spreadsheet/SpreadsheetEditor.js#L51) A solution would be to initialise `this.state.url` to `attributes.url` instead of the current `''` ([here](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Spreadsheet/SpreadsheetEditor.js#L48))
> 
> I don't think the attributes object is visible at that point. So I set it on renderEdit(). Let me know if it's ok 👌

`props.attributes.url` should be available? 🤔

**Comment by dpivo** [comment]
> > > This will cause a delay when typing in the input, since the attributes' url is updated with a [debounce function](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Spreadsheet/SpreadsheetEditor.js#L51) A solution would be to initialise `this.state.url` to `attributes.url` instead of the current `''` ([here](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Spreadsheet/SpreadsheetEditor.js#L48))
> > 
> > 
> > I don't think the attributes object is visible at that point. So I set it on renderEdit(). Let me know if it's ok ok_hand
> 
> `props.attributes.url` should be available? thinking

ah right, yes. I implemented the change, thanks! :pray:

**Review by mleray — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
