### PR TITLE
PLANET-7425 Fix ignore_categories behaviour for the Articles block

### PR DESCRIPTION
**Pull request by mleray**
### Description

See [PLANET-7425](https://jira.greenpeace.org/browse/PLANET-7425)

**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2212

### Testing

Both in Pages and Posts, the `ignore_categories` attribute should now work as expected!

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [rhea](https://www-dev.greenpeace.org/test-rhea) | [admin](https://www-dev.greenpeace.org/test-rhea/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-rhea/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-rhea) | [composer-local.json](https://github.com/greenpeace/planet4-test-rhea/blob/main/composer-local.json)

:watch: 2024.02.06 12:28:11

**Comment by sagarsdeshmukh** [comment]
Hi Maud,
Now, the 'Ignore Categories' checkbox works as intended; it ignores the current post/page category filter in the articles list. However, when the checkbox is not selected, shouldn't the articles block display all articles belonging to the current page/post category?

I am currently testing [this post](https://www-dev.greenpeace.org/test-rhea/story/1718/test-articles-block/) with the "Energy" category assigned, and the 'Ignore Category' checkbox is unchecked in the articles block. In this case, shouldn't the articles block populate with posts from the "Energy" category? Strangely, the articles list is blank.

**Comment by mleray** [comment]
@sagarsdeshmukh can you please test again? 🙏

**Review by sagarsdeshmukh — APPROVED** [review]
Tested on local, PR looks good to me 👍

**Pull request merged**
