### PR TITLE
PLANET-7548: Remove Action pattern block from plugin

### PR DESCRIPTION
**Pull request by GP-Dan-Tovbein**
Ref: https://jira.greenpeace.org/browse/PLANET-7548

# Description
Include all related files

Related PRs
- https://github.com/greenpeace/planet4-master-theme/pull/2338

## Testing
Check it out this [demo page](https://www-dev.greenpeace.org/test-pluto/take-pattern-block-demo-page/) which is using the assigned dev instance for testing. 
Also disabled the P4 Gutenberg plugin from [here](https://www-dev.greenpeace.org/test-pluto/wp-admin/plugins.php?plugin_status=all&paged=1&s).

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [pluto](https://www-dev.greenpeace.org/test-pluto) | [admin](https://www-dev.greenpeace.org/test-pluto/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-pluto/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pluto) | [composer-local.json](https://github.com/greenpeace/planet4-test-pluto/blob/main/composer-local.json)

:watch: 2024.07.31 11:16:20

**Comment by mleray** [comment]
@GP-Dan-Tovbein I think that this PR needs to be rebased!

**Review by mardelnet — APPROVED** [review]
Good job, @dantovbein

**Comment by comzeradd** [comment]
Revert this commit since we https://github.com/greenpeace/planet4-master-theme/pull/2338 is ready to be merged. @GP-Dan-Tovbein you may have to re-open this.

**Pull request merged**
