### PR TITLE
PLANET-7445: Remove the "Split 2 Columns" block

### PR DESCRIPTION
**Pull request by mardelnet**
Ref: https://jira.greenpeace.org/browse/PLANET-7445

<hr>

**DESCRIPTION:**
This PR removes the Split Two Columns block.
It has to be merged once the migration script of the Split Two Columns block is completed.

<hr>

**RELATED PR:**
https://github.com/greenpeace/planet4-master-theme/pull/2433

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [titan](https://www-dev.greenpeace.org/test-titan) | [admin](https://www-dev.greenpeace.org/test-titan/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-titan/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-titan) | [composer-local.json](https://github.com/greenpeace/planet4-test-titan/blob/main/composer-local.json)

:watch: 2024.11.05 14:12:12

**Review by mleray — COMMENTED** [review]
You forgot to remove the [CSS files](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/tree/main/assets/src/styles/blocks/SplitTwoColumns) 
I also found these 2 images, not 100% sure that they are related to the block tbh 😬 But they are used nowhere so should be safe to remove:
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/public/images/plastic/split-column-mobile.svg
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/public/images/plastic/split-column-desktop.svg

**Comment by mardelnet** [comment]
> You forgot to remove the [CSS files](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/tree/main/assets/src/styles/blocks/SplitTwoColumns) I also found these 2 images, not 100% sure that they are related to the block tbh 😬 But they are used nowhere so should be safe to remove:

Nice catch! Files were removed.

**Review by mleray — APPROVED** [review]
Looks good to me 🧹 👍

**Pull request merged**
