### PR TITLE
PLANET-7378: Make sure to not instantiate twice the Happypoint class

### PR DESCRIPTION
**Pull request by GP-Dan-Tovbein**
Ref: [PLANET-7378](https://jira.greenpeace.org/browse/PLANET-7378)

# Description
Move the Happypoint block to master-theme

**Related theme's PR**
- https://github.com/greenpeace/planet4-master-theme/pull/2184

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [titan](https://www-dev.greenpeace.org/test-titan) | [admin](https://www-dev.greenpeace.org/test-titan/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-titan/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-titan) | [composer-local.json](https://github.com/greenpeace/planet4-test-titan/blob/main/composer-local.json)

:watch: 2023.12.29 13:06:13

**Review by mleray — APPROVED** [review]
👍

**Comment by GP-Dan-Tovbein** [comment]
@mleray I've just updated this PR and removed the data endpoint

**Comment by mleray** [comment]
> @mleray I've just updated this PR and removed the data endpoint

We still need to have it here, the Happypoint block (and therefore the endpoint) is only registered in the master theme if the `Planet 4 Blocks` feature is enabled...

**Comment by GP-Dan-Tovbein** [comment]
> > @mleray I've just updated this PR and removed the data endpoint
> 
> We still need to have it here, the Happypoint block (and therefore the endpoint) is only registered in the master theme if the `Planet 4 Blocks` feature is enabled...

Oh you're 100% right

**Pull request merged**
