### PR TITLE
A11y: Convert carousel anchors to buttons

### PR DESCRIPTION
**Pull request by aeisenberg**
Partial fix for:
Ref: https://github.com/greenpeace/planet4/issues/125

Accessibility fix: convert anchors into buttons on the carousels.

### CODE REVIEW

**Review by mleray — CHANGES_REQUESTED** [review]
I've tested your changes for the GalleryCarousel on local and it looks good to me 👍
However your changes for `CarouselHeader_full_width_classic.scss` and `CarouselHeader.scss` should go together with updating the corresponding [twig template](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/templates/blocks/carousel_header_full-width-classic.twig#L70)... But I don't think we actually need to update that component right now since it's being [converted to WYSIWYG](https://jira.greenpeace.org/browse/PLANET-4809) 🤔 So I think you can revert these changes and just update the GalleryCarousel for now!

**Comment by aeisenberg** [comment]
Thanks for the review. I addressed your comments and I haven't (yet) looked at the failing tests. Hmmmm....

Also, I have some questions on https://github.com/greenpeace/planet4/issues/125, would you be able to answer them?

**Review by mleray — APPROVED** [review]
Looks good to me 👍

**Comment by aeisenberg** [comment]
It _looks_ like the `main` check is failing because I don't have access. 

> request-instance - Unauthorized

Is this OK to merge as-is, or should this be fixed before merging?

**Comment by mleray** [comment]
> It _looks_ like the `main` check is failing because I don't have access.
> 
> > request-instance - Unauthorized
> 
> Is this OK to merge as-is, or should this be fixed before merging?

This would be to deploy your changes to one of our test instances, indeed you are probably missing some permissions for that... But I've tested it on local so it's okay to merge as is 🙂

**Pull request merged**
