### PR TITLE
Remove Take Action Boxout block

### PR DESCRIPTION
**Pull request by mleray**
### Description

This is in preparation for [PLANET-7512](https://jira.greenpeace.org/browse/PLANET-7512), since this block has been moved to the theme we can remove it from the plugin and avoid potential style conflicts.

**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2365

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [pandora](https://www-dev.greenpeace.org/test-pandora) | [admin](https://www-dev.greenpeace.org/test-pandora/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-pandora/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pandora) | [composer-local.json](https://github.com/greenpeace/planet4-test-pandora/blob/main/composer-local.json)

:watch: 2024.09.03 10:33:39

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [pandora](https://www-dev.greenpeace.org/test-pandora) | [admin](https://www-dev.greenpeace.org/test-pandora/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-pandora/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pandora) | [composer-local.json](https://github.com/greenpeace/planet4-test-pandora/blob/main/composer-local.json)

:watch: 2024.09.03 10:52:47

**Review by mardelnet — COMMENTED** [review]
@mleray 
Both on my local installation and also on the [test instance](https://www-dev.greenpeace.org/test-pandora), the Take Action Boxout can only used or be added to a post/page when the P4 plugin is disabled.
Would you mind checking it?

**Review by mardelnet — COMMENTED** [review]
@mleray 
When the P4 plugin is active, the Take Action Boxout block can only be added to posts.
When the plugin is inactive, the block can be added to posts and pages (and maybe other post types, haven't checked it).
Is that something expected?

**Comment by mleray** [comment]
> @mleray When the P4 plugin is active, the Take Action Boxout block can only be added to posts. When the plugin is inactive, the block can be added to posts and pages (and maybe other post types, haven't checked it). Is that something expected?

@mardelnet this is because in the plugin we have this [filter](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/planet4-gutenberg-blocks.php#L310-L315) to allow certain blocks for certain post types only. As far as I know, this hasn't been moved to the theme so for now it is expected, yes. Actually for this block in particular, I'm pretty sure there have been conversations about allowing it in other post types too so that might be a good thing 🤔 Pinging @comzeradd for confirmation!

**Comment by comzeradd** [comment]
> I'm pretty sure there have been conversations about allowing it in other post types too so that might be a good thing

Yes, we have that in [PLANET-7534](https://jira.greenpeace.org/browse/PLANET-7534). So for it's fine for this PR. I'll make a follow up ticket to move the block filters to the theme.

**Review by mardelnet — APPROVED** [review]
Good job, @mleray 
I love to see this: 
Screenshot from 2024-09-04 11-38-12

**Pull request merged**
