### PR TITLE
PLANET-6958: Remove deprecated multiline prop

### PR DESCRIPTION
**Pull request by GP-Dan-Tovbein**
## Description
[PLANET-6958](https://jira.greenpeace.org/browse/PLANET-6958).

### Related PRs
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1042

### External Resources
- [Migrate to InnerBlocks](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/nested-blocks-inner-blocks/)

### CODE REVIEW

**Comment by comzeradd** [comment]
So following up @mleray's comment from the other PR, now in these fields editors will be able to add multiple lines with this change. But looking at where this is currently being used, I see it's just for headers, where it should be ok to remove because I don't expect anyone to start adding multiple lines of `h2` text there.

Have you seen any other use case for this?

**Comment by GP-Dan-Tovbein** [comment]
> So following up @mleray's comment from the other PR, now in these fields editors will be able to add multiple lines with this change. But looking at where this is currently being used, I see it's just for headers, where it should be ok to remove because I don't expect anyone to start adding multiple lines of `h2` text there.
> 
> Have you seen any other use case for this?

Yes [here](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/assets/src/blocks/ENForm/ENFormInPlaceEdit.js#L277), which is the only place, in our code, that is using the `multiline` prop.

**Comment by mleray** [comment]
> Yes [here](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/assets/src/blocks/ENForm/ENFormInPlaceEdit.js#L277), which is the only place, in our code, that is using the `multiline` prop.

We should also remove these ones right? Not just the places where we set `multiline` to `false`.

**Comment by mleray** [comment]
What about [this one](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/assets/src/blocks/ENForm/ENFormInPlaceEdit.js#L277)?

**Review by mleray — APPROVED** [review]
👍

**Comment by GP-Dan-Tovbein** [comment]
Unfortunately the `multiline` prop doesn't work even you set to `true` or `false`. Then, in favor of that, we'll proceed to remove it at all and proceed to the refactor of some blocks (as `<InnerBlocks/>`).
Here is an example of the [Accordion refactoring ticket](https://jira.greenpeace.org/browse/PLANET-7272).

**Pull request merged**
