### PR TITLE
Allow multiple boxouts, remove id attribute

### PR DESCRIPTION
**Pull request by Inwerpsel**
* Block now is inline so multiple should work.

[This master theme PR](https://github.com/greenpeace/planet4-master-theme/pull/1538) needs to be merged first.

Example on test instance: https://www-dev.greenpeace.org/test-iocaste/story/30102/the-story-of-plastic-is-an-eye-opener-on-the-global-plastic-pollution-crisis/

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [iocaste](https://www-dev.greenpeace.org/test-iocaste) | [admin](https://www-dev.greenpeace.org/test-iocaste/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-iocaste/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-iocaste) | [composer-local.json](https://github.com/greenpeace/planet4-test-iocaste/blob/main/composer-local.json)

:watch: 2021.12.07 10:33:04

**Review by mleray — APPROVED** [review]
Looks good to me 👍 Maybe you could add the ticket number in the commit before merging?

**Comment by Inwerpsel** [comment]
> Looks good to me +1 Maybe you could add the ticket number in the commit before merging?

This also works for the Jira integration 
Screenshot from 2021-12-07 13-58-16

**Comment by comzeradd** [comment]
> This also works for the Jira integration

Not super important indeed for the integration, but the reason we add the ticket number in the commit message is to provide [context](https://support.greenpeace.org/planet4/development/git-guidelines#context). It's already in the description, but it's visually much easier to identify/find commits that belong to a ticket when browsing the git log. A bit tedious I know, that's why we don't enforce it, but I've found it very useful in the past.

**Comment by Inwerpsel** [comment]
Sorry for not being more specific in my previous message. The screenshot is from the commit message and I meant it also works for the Jira integration if it's in the body.

**Comment by Inwerpsel** [comment]
And that way it can be a clickable link, which is better on Github.

**Pull request merged**
