### PR TITLE
Remove Cover's block campaign style and relevant test

### PR DESCRIPTION
**Pull request by sagarsdeshmukh**
Ref. https://jira.greenpeace.org/browse/PLANET-7489

[Related PR](https://github.com/greenpeace/planet4-master-theme/pull/2349)

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [oberon](https://www-dev.greenpeace.org/test-oberon) | [admin](https://www-dev.greenpeace.org/test-oberon/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-oberon/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-oberon) | [composer-local.json](https://github.com/greenpeace/planet4-test-oberon/blob/main/composer-local.json)

:watch: 2024.09.02 05:19:27

**Comment by sagarsdeshmukh** [comment]
> Good job, @sagarsdeshmukh I still see some mentions of the Campaign Covers block in the following files. Would you mind taking a look at them?
> 
> * classes/blocks/class-covers.php
> * tests/e2e/tools/lib/covers.js
> * assets/src/styles/blocks/Covers/styles/CampaignCovers.scss
> * assets/src/styles/blocks/Covers/CoversStyle.scss
> * assets/src/blocks/Covers/useCovers.js
> * assets/src/blocks/Covers/CoversEditor.js
> * assets/src/blocks/Covers/CoversConstants.js
> * assets/src/blocks/Covers/Covers.js
> * assets/src/blocks/Covers/CampaignCovers.js

Yes, that is true. We have other variations of cover block and here in this PR I am focusing on a soft delete(hide campaign cover style option on add covers blocks editor page)campaign covers style only.

**Comment by mardelnet** [comment]
> Yes, that is true. We have other variations of cover block and here in this PR I am focusing on a soft delete(hide campaign cover style option on add covers blocks editor page)campaign covers style only.

So, is it okay to keep the files I mentioned?
If so, I'm ready to approve this PR.

**Comment by sagarsdeshmukh** [comment]
> > Yes, that is true. We have other variations of cover block and here in this PR I am focusing on a soft delete(hide campaign cover style option on add covers blocks editor page)campaign covers style only.
> 
> So, is it okay to keep the files I mentioned? If so, I'm ready to approve this PR.

We have 2 more cover style migration tickets. Once they are all OK, we can remove the whole cover block code in one go. that's why I didn't disturb the whole covers block.

**Review by mardelnet — APPROVED** [review]

**Comment by sagarsdeshmukh** [comment]
Covers block moved to the master theme, hence closing the PR

**Pull request closed without merging**
