### PR TITLE
Revert "PLANET-4233 Campaigns columns block admin warnings improvements"

### PR DESCRIPTION
**Pull request by sagarsdeshmukh**
Reverts greenpeace/planet4-plugin-gutenberg-blocks#130

### CODE REVIEW

**Comment by Inwerpsel** [comment]
> Please remove the deps.json files. I will make a PR to exclude them in the future

You mean in this PR? Or drop this PR and make a PR that just removes those files?

**Comment by dpivo** [comment]
> > Please remove the deps.json files. I will make a PR to exclude them in the future
> 
> You mean in this PR? Or drop this PR and make a PR that just removes those files?

Just in this PR. I will make another PR that adds them to the gitignore file

**Comment by comzeradd** [comment]
Per #134 I think we can close that one, right?

**Comment by Inwerpsel** [comment]
Closed per https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/134

**Pull request closed without merging**
