### PR TITLE
PLANET-6781: Block report - pagination, block style, api

### PR DESCRIPTION
**Pull request by lithrel**
Ref: https://jira.greenpeace.org/browse/PLANET-6781

### Pagination
Block report is paginated, which greatly reduces page weight
Screenshot from 2022-06-17 16-17-09

### Revision of nonce handling
WordPress uses a redirection scheme to verify nonce, filter parameters and redirect to the proper page.
We use the same system here, with a hook on `admin_action_*`, this allows to switch to GET mode and simplifies url handling.

### Block style listed in table
Style used for a block is listed in the search results (detection based on classname)
Screenshot from 2022-06-17 12-44-33
It is always possible to search for a specific style by searching for its name in the search box, ie `is-style-cta` will return all blocks with this string in their attributes.

### API v3

Attempt at an API replacement, that includes all pages, blocks and styles
```shell
> curl -k https://www.planet4.test/wp-json/plugin_blocks/v3/plugin_blocks_report/ | jq 
```
<details>
<summary>Response</summary>
<pre>
{
  "block_types": {
    "core-embed/facebook": 4,
    "core-embed/instagram": 2,
    "core-embed/reddit": 1,
    "core-embed/twitter": 13,
    "core-embed/vimeo": 1,
    "core-embed/wordpress": 1,
    "core-embed/youtube": 38,
    "core/block": 31,
    "core/button": 21,
    "core/buttons": 19,
    "core/column": 2,
    "core/columns": 1,
    "core/embed": 163,
    "core/file": 3,
    "core/group": 30,
    "core/heading": 1415,
    "core/html": 95,
    "core/image": 1874,
    "core/list": 241,
    "core/media-text": 16,
    "core/paragraph": 13082,
    "core/quote": 3,
    "core/separator": 117,
    "core/shortcode": 12,
    "core/spacer": 39,
    "core/table": 6,
    "planet4-blocks/articles": 38,
    "planet4-blocks/carousel-header": 9,
    "planet4-blocks/columns": 117,
    "planet4-blocks/cookies": 1,
    "planet4-blocks/counter": 4,
    "planet4-blocks/covers": 65,
    "planet4-blocks/enform": 19,
    "planet4-blocks/gallery": 126,
    "planet4-blocks/happypoint": 30,
    "planet4-blocks/media-video": 24,
    "planet4-blocks/social-media": 7,
    "planet4-blocks/spreadsheet": 3,
    "planet4-blocks/submenu": 2,
    "planet4-blocks/take-action-boxout": 375,
    "planet4-blocks/timeline": 5
  },
  "block_styles": {
    "core-embed/facebook": {
      "": 4
    },
    "core-embed/instagram": {
      "": 2
    },
    "core-embed/reddit": {
      "": 1
    },
    "core-embed/twitter": {
      "": 13
    },
    "core-embed/vimeo": {
      "": 1
    },
    "core-embed/wordpress": {
      "": 1
    },
    "core-embed/youtube": {
      "": 38
    },
    "core/block": {
      "": 31
    },
    "core/button": {
      "": 15,
      "cta": 6
    },
    "core/buttons": {
      "": 19
    },
    "core/column": {
      "": 2
    },
    "core/columns": {
      "": 1
    },
    "core/embed": {
      "": 163
    },
    "core/file": {
      "": 3
    },
    "core/group": {
      "": 30
    },
    "core/heading": {
      "": 1415
    },
    "core/html": {
      "": 95
    },
    "core/image": {
      "": 1874
    },
    "core/list": {
      "": 241
    },
    "core/media-text": {
      "": 15,
      "default": 1
    },
    "core/paragraph": {
      "": 13082
    },
    "core/quote": {
      "": 3
    },
    "core/separator": {
      "": 98,
      "default": 3,
      "wide": 16
    },
    "core/shortcode": {
      "": 12
    },
    "core/spacer": {
      "": 39
    },
    "core/table": {
      "": 2,
      "regular": 1,
      "stripes": 3
    },
    "planet4-blocks/articles": {
      "": 38
    },
    "planet4-blocks/carousel-header": {
      "": 9
    },
    "planet4-blocks/columns": {
      "": 42,
      "image": 43,
      "no_image": 16,
      "tasks": 16
    },
    "planet4-blocks/cookies": {
      "": 1
    },
    "planet4-blocks/counter": {
      "": 3,
      "en-forms-bar": 1
    },
    "planet4-blocks/covers": {
      "": 17,
      "campaign": 14,
      "content": 5,
      "take-action": 29
    },
    "planet4-blocks/enform": {
      "": 18,
      "side-style": 1
    },
    "planet4-blocks/gallery": {
      "": 112,
      "grid": 5,
      "slider": 9
    },
    "planet4-blocks/happypoint": {
      "": 30
    },
    "planet4-blocks/media-video": {
      "": 24
    },
    "planet4-blocks/social-media": {
      "": 7
    },
    "planet4-blocks/spreadsheet": {
      "": 3
    },
    "planet4-blocks/submenu": {
      "": 2
    },
    "planet4-blocks/take-action-boxout": {
      "": 375
    },
    "planet4-blocks/timeline": {
      "": 5
    }
  },
  "post_types": {
    "archive": 12423,
    "campaign": 21,
    "p4_action": 2,
    "page": 73,
    "post": 1496
  }
}
</pre>
</details>

This version has a different structure than v2 - v2 is designed to easily fit in google sheet, but I wasn't sure how to organize this to account for styles. This data would also be a good candidate for Grafana, so I could give it a try.

## Test

Deployed on [Saturn test instance](https://www-dev.greenpeace.org/test-saturn/wp-admin/admin.php?page=plugin_blocks_report_beta)

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [saturn](https://www-dev.greenpeace.org/test-saturn) | [admin](https://www-dev.greenpeace.org/test-saturn/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-saturn/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-saturn) | [composer-local.json](https://github.com/greenpeace/planet4-test-saturn/blob/main/composer-local.json)

:watch: 2022.06.17 15:01:18

**Comment by lithrel** [comment]
Yep makes sense, I'll take the second one to avoid style name collision with `total` :ok_hand:

**Comment by comzeradd** [comment]
> does the proposition includes removing the unspecified style as empty string `""` ?

We can include it but maybe with a name? (eg. "unspecified" or "n/a")
Have you figure out why we have so many like this?

**Comment by lithrel** [comment]
A mix of how we use default styles and how we detect it here.
Because styles are declared in frontend files, the backend doesn't know about it, so detection is based on class name `is-style-*`.
When no style is specified, a block uses the style declared as `isDefault: true`, but doesn't write (or _we_ don't write ?) its default class name (adding a Covers block will use Content covers by default, but checking the code will show no class name).
Declaration of style and default style not being available, I can't confidently deduce anything and so leave it empty.
I thought about declaring styles in predefined json files so frontend and backend can use it, but we also use js constants in there - I don't know if it's worth going back to share declarations

**Review by comzeradd — APPROVED** [review]
Looks good 💯 

Once released we can adjust the report sheet script code to use and match v3 api endpoint.

**Pull request merged**
