### PR TITLE
Maintenance: Upgrade to NodeJS 16

### PR DESCRIPTION
**Pull request by GP-Dan-Tovbein**
Ref: [PLANET-6462](https://jira.greenpeace.org/browse/PLANET-6462)

### Description
We're going to upgrade to latest LTS `Node.js` version gradually, and make sure that everything is still working properly.

#### Related PRs:
- Docker Compose: [#113](https://github.com/greenpeace/planet4-docker-compose/pull/113)
- Master theme: [#1885](https://github.com/greenpeace/planet4-master-theme/pull/1885)

_Before starting the upgrade, just run_ `$ npm doctor` _to see which versions are currently recommended._
In my case I get:
```bash
Check                               Value                        Recommendation
npm ping                            ok
npm -v                              v6.14.17                     Use npm v9.4.1
node -v                             v14.19.3                     Use node v18.13.0
npm config get registry             https://registry.npmjs.org/
which git                           /usr/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   notOk 
```

#### First upgrade: 
`Node.js 16.19.0 | Gallium` and `npm 8.19.3`
```
  "engines" : {
    "npm" : ">=8.0.0 <9.0.0",
    "node" : ">=16.0.0 <17.0.0"
  }
```

#### Expected upgrade:
`Node.js 18.13.0 | Hydrogen` and `npm 8.19.3`

```
  "engines" : {
    "npm" : ">=8.0.0 <9.0.0",
    "node" : ">=18.0.0 <19.0.0"
  }
```
For more information, please check the [Node.js releases page](https://nodejs.org/en/download/releases/)

#### From Docker Compose
First, make sure to run the docker-compose, ideally the **full** version, with `Node.js 16`
`NODE_IMAGE=node:16-alpine3.16 COMPOSE_FILE=docker-compose.full.yml make run`

Within `M*` architecture run this command:
`NODE_IMAGE=node:16-alpine3.16 DOCKER_DEFAULT_PLATFORM=linux/amd64 REDIS_IMAGE=arm64v8/redis:4-stretch COMPOSE_FILE=docker-compose.full.yml make run`

Once the `docker-compose` is running, then:

```bash
docker-compose exec -u node node sh -c "cd app/source/public/wp-content/plugins/planet4-plugin-gutenberg-blocks \
&& rm -rf node-modules package-lock.json \
&& npm cache clear --force \
&& npm uninstall node-sass \
&& npm install --save-dev sass css-loader mini-css-extract-plugin \
&& npm run build"
```
After that, then check both versions:

```bash
docker-compose exec -u node node sh -c "cd app/source/public/wp-content/plugins/planet4-plugin-gutenberg-blocks \
&& node --version \
&& npm --version"
```
With these expected versions:
```log
v16.19.0
8.19.3
```

#### From your local environment

1. Install all dependencies `$ npm install`
2. Build the project `$ npm run build`

If it was building without errors that means that the current node version is working as expected.

#### About `node-sass`
Since the library [has been deprecated](https://sass-lang.com/blog/libsass-is-deprecated) at the end of 2022, they request to migrate to `sass` instead.

### M* architecture workarounds
In case you need to rollback to a previous version using `nvm`, like `nvm use 14`, you will probably get this error:
`npm ERR! zlib: incorrect data check`

1. Remove `nvm` cache: `$ nvm cache clear`
2. Verify your `arm` by just running `$ arm`, you'll probably have set `arm64`
3. Change the `arch` to your shell, in my case I use `zsh`: `$ arch -x86_64 zsh` 
4. Install the new version: `$ nvm install 14 --shared-zlib`
6. Build again the project `$ npm run build`. It should be working now!
7. Finally, run `$ exit` to use again `arm64`.

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [neptune](https://www-dev.greenpeace.org/test-neptune) | [admin](https://www-dev.greenpeace.org/test-neptune/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-neptune/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-neptune) | [composer-local.json](https://github.com/greenpeace/planet4-test-neptune/blob/main/composer-local.json)

:watch: 2023.03.17 14:39:33

**Comment by comzeradd** [comment]
Locally during the `npm install` process I get some dependencies conflict errors (despite build finishing successfully) and in the end I get a diff on `package-lock.json`. Maybe it's not updated with the latest changes?

`docker-compose exec -u node node sh -c 'cd /app/source/public/wp-content/plugins/planet4-plugin-gutenberg-blocks   && npm install --no-audit --progress=false'`

<details>
  <summary>Output error messages</summary>

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: reakit@1.3.11
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   peer react@">=16.3.0" from @emotion/core@10.3.1
npm WARN   node_modules/@emotion/core
npm WARN     peer @emotion/core@"^10.0.22" from @emotion/styled@10.0.23
npm WARN     node_modules/@emotion/styled
npm WARN     1 more (@emotion/styled-base)
npm WARN   6 more (@emotion/styled, @emotion/styled-base, downshift, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0" from reakit@1.3.11
npm WARN node_modules/reakit
npm WARN   reakit@"^1.0.0-beta.12" from @wordpress/components@8.5.0
npm WARN   node_modules/@wordpress/components
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0" from reakit@1.3.11
npm WARN   node_modules/reakit
npm WARN     reakit@"^1.0.0-beta.12" from @wordpress/components@8.5.0
npm WARN     node_modules/@wordpress/components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: reakit@1.3.11
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0 || ^17.0.0" from reakit@1.3.11
npm WARN node_modules/reakit
npm WARN   reakit@"^1.0.0-beta.12" from @wordpress/components@8.5.0
npm WARN   node_modules/@wordpress/components
npm WARN 
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.8.0 || ^17.0.0" from reakit@1.3.11
npm WARN   node_modules/reakit
npm WARN     reakit@"^1.0.0-beta.12" from @wordpress/components@8.5.0
npm WARN     node_modules/@wordpress/components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: reakit-system@0.15.2
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   peer react@">=16.3.0" from @emotion/core@10.3.1
npm WARN   node_modules/@emotion/core
npm WARN     peer @emotion/core@"^10.0.22" from @emotion/styled@10.0.23
npm WARN     node_modules/@emotion/styled
npm WARN     1 more (@emotion/styled-base)
npm WARN   6 more (@emotion/styled, @emotion/styled-base, downshift, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0" from reakit-system@0.15.2
npm WARN node_modules/reakit-system
npm WARN   reakit-system@"^0.15.2" from reakit@1.3.11
npm WARN   node_modules/reakit
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0" from reakit-system@0.15.2
npm WARN   node_modules/reakit-system
npm WARN     reakit-system@"^0.15.2" from reakit@1.3.11
npm WARN     node_modules/reakit
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: reakit-system@0.15.2
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0 || ^17.0.0" from reakit-system@0.15.2
npm WARN node_modules/reakit-system
npm WARN   reakit-system@"^0.15.2" from reakit@1.3.11
npm WARN   node_modules/reakit
npm WARN 
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.8.0 || ^17.0.0" from reakit-system@0.15.2
npm WARN   node_modules/reakit-system
npm WARN     reakit-system@"^0.15.2" from reakit@1.3.11
npm WARN     node_modules/reakit
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: reakit-utils@0.15.2
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   peer react@">=16.3.0" from @emotion/core@10.3.1
npm WARN   node_modules/@emotion/core
npm WARN     peer @emotion/core@"^10.0.22" from @emotion/styled@10.0.23
npm WARN     node_modules/@emotion/styled
npm WARN     1 more (@emotion/styled-base)
npm WARN   6 more (@emotion/styled, @emotion/styled-base, downshift, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0" from reakit-utils@0.15.2
npm WARN node_modules/reakit-utils
npm WARN   reakit-utils@"^0.15.2" from reakit@1.3.11
npm WARN   node_modules/reakit
npm WARN   2 more (reakit-system, reakit-warning)
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0" from reakit-utils@0.15.2
npm WARN   node_modules/reakit-utils
npm WARN     reakit-utils@"^0.15.2" from reakit@1.3.11
npm WARN     node_modules/reakit
npm WARN     2 more (reakit-system, reakit-warning)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: reakit-utils@0.15.2
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0 || ^17.0.0" from reakit-utils@0.15.2
npm WARN node_modules/reakit-utils
npm WARN   reakit-utils@"^0.15.2" from reakit@1.3.11
npm WARN   node_modules/reakit
npm WARN   2 more (reakit-system, reakit-warning)
npm WARN 
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.8.0 || ^17.0.0" from reakit-utils@0.15.2
npm WARN   node_modules/reakit-utils
npm WARN     reakit-utils@"^0.15.2" from reakit@1.3.11
npm WARN     node_modules/reakit
npm WARN     2 more (reakit-system, reakit-warning)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: reakit-warning@0.6.2
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   peer react@">=16.3.0" from @emotion/core@10.3.1
npm WARN   node_modules/@emotion/core
npm WARN     peer @emotion/core@"^10.0.22" from @emotion/styled@10.0.23
npm WARN     node_modules/@emotion/styled
npm WARN     1 more (@emotion/styled-base)
npm WARN   6 more (@emotion/styled, @emotion/styled-base, downshift, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0" from reakit-warning@0.6.2
npm WARN node_modules/reakit-warning
npm WARN   reakit-warning@"^0.6.2" from reakit@1.3.11
npm WARN   node_modules/reakit
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0" from reakit-warning@0.6.2
npm WARN   node_modules/reakit-warning
npm WARN     reakit-warning@"^0.6.2" from reakit@1.3.11
npm WARN     node_modules/reakit
```
</details>

---

I don't see the above in the CI, maybe because we run `npm ci` there and it sticks to the lock file. But in the end tests are failing because the blocks haven't been build successfully:

```
ERROR in ./assets/src/blocks/Covers/CoversCarouselLayout.js
    Module not found: Error: Can't resolve 'uuid' in '/home/circleci/*******-plugin-gutenberg-blocks/assets/src/blocks/Covers'
     @ ./assets/src/blocks/Covers/CoversCarouselLayout.js 5:0-34 12:34-38
     @ ./assets/src/blocks/Covers/CoversFrontend.js
     @ ./assets/src/blocks/Covers/CoversScript.js
 ```

**Comment by GP-Dan-Tovbein** [comment]
> Locally during the `npm install` process I get some dependencies conflict errors (despite build finishing successfully) and in the end I get a diff on `package-lock.json`. Maybe it's not updated with the latest changes?
> 
> `docker-compose exec -u node node sh -c 'cd /app/source/public/wp-content/plugins/planet4-plugin-gutenberg-blocks && npm install --no-audit --progress=false'`
> Output error messages
> 
> I don't see the above in the CI, maybe because we run `npm ci` there and it sticks to the lock file. But in the end tests are failing because the blocks haven't been build successfully:
> 
> ```
> ERROR in ./assets/src/blocks/Covers/CoversCarouselLayout.js
>     Module not found: Error: Can't resolve 'uuid' in '/home/circleci/*******-plugin-gutenberg-blocks/assets/src/blocks/Covers'
>      @ ./assets/src/blocks/Covers/CoversCarouselLayout.js 5:0-34 12:34-38
>      @ ./assets/src/blocks/Covers/CoversFrontend.js
>      @ ./assets/src/blocks/Covers/CoversScript.js
> ```

Hey @comzeradd ! I've rebased and updated the PR and it seems to be working properly now.

**Comment by comzeradd** [comment]
The error in the pipeline is still there, thus all the block tests are failing. Search for `ERROR` in the [build job](https://app.circleci.com/pipelines/github/greenpeace/planet4-plugin-gutenberg-blocks/7565/workflows/08e7873f-f2fe-4317-add1-506a17166e72/jobs/40592/parallel-runs/0/steps/0-104)

**Comment by comzeradd** [comment]
`package-lock.json` is fine now 👍🏻 But I still see the dependency conflict errors I pasted above. Not sure if these are related on why the block fail to build in the pipeline

**Review by comzeradd — APPROVED** [review]
I still see some conflicts locally during `npm install` but everything builds fine now and tests pass :+1:

**Pull request merged**
