### PR TITLE
PLANET-6041 Use less deep styleguide folders, remove unused file

### PR DESCRIPTION
**Pull request by Inwerpsel**
Ref: https://jira.greenpeace.org/browse/PLANET-6041

---

Bump master theme to version with less deep folders for the styleguide parts.

When doing the substitutions, I noticed that `assets/src/styles/blocks/ENForm/style.scss` has some incorrect imports, but it's also not used, so I removed it.

### CODE REVIEW

**Comment by Inwerpsel** [comment]
Not sure why the CI workflow seems to check out the master commit of the submodule, even though this PR updates it to a commit of my branch there :confused:  https://app.circleci.com/pipelines/github/greenpeace/planet4-plugin-gutenberg-blocks/4065/workflows/acac20e7-ce8c-46ac-9245-8c8c3eab458d/jobs/14402

**Comment by Inwerpsel** [comment]
> Not sure why the CI workflow seems to check out the master commit of the submodule, even though this PR updates it to a commit of my branch there  https://app.circleci.com/pipelines/github/greenpeace/planet4-plugin-gutenberg-blocks/4065/workflows/acac20e7-ce8c-46ac-9245-8c8c3eab458d/jobs/14402

Seems like that's what it always did :sweat_smile: https://github.com/greenpeace/planet4-builder/pull/80

**Review by lithrel — APPROVED** [review]
:+1:  tested locally with https://github.com/greenpeace/planet4-master-theme/pull/1359

Could be good to update `./docs/theme` data to fit this change

**Comment by Inwerpsel** [comment]
>  tested locally with [greenpeace/planet4-master-theme#1359](https://github.com/greenpeace/planet4-master-theme/pull/1359)
> 
> Could be good to update `./docs/theme` data to fit this change

Yeah that's already outdated in multiple ways, I'll remove or replace it soon :ok:

**Pull request merged**
