### PR TITLE
PLANET-6006 Align Gallery carousel with design system

### PR DESCRIPTION
**Pull request by mleray**
### Description

See https://jira.greenpeace.org/browse/PLANET-6006

Related PR: [master-theme](https://github.com/greenpeace/planet4-master-theme/pull/1506)

This PR also includes adding swipe on mobile (using Hammer) and splitting the block's files. It also removes the no longer used carousel indicator color variable  🎉 

### Testing

You can test the new Gallery carousel in all screen sizes on [this page](https://www-dev.greenpeace.org/test-atlas/act/sail-aboard-a-greenpeace-ship/) for example, or you can simply add one to a page on local 🙂

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [atlas](https://www-dev.greenpeace.org/test-atlas) | [admin](https://www-dev.greenpeace.org/test-atlas/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-atlas/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-atlas) | [composer-local.json](https://github.com/greenpeace/planet4-test-atlas/blob/main/composer-local.json)

:watch: 2021.11.04 15:57:46

**Review by comzeradd — DISMISSED** [review]
Code looks good :+1:

On mobile we don't have swipe function right? I assume we don't have one in the current version as well.

**Comment by mleray** [comment]
> On mobile we don't have swipe function right? I assume we don't have one in the current version as well.

Magali actually wanted to add it in this new version because it has no arrows on mobile, but she forgot to add that to the ticket tasks... She noticed that while doing UAT, so she then added it to the ticket and I'm looking into it!

**Review by comzeradd — APPROVED** [review]
Did another check and block works great. Swipe also works now on mobile.

**Pull request merged**
