### PR TITLE
PLANET-7549: Remove Campaign pattern block from plugin

### PR DESCRIPTION
**Pull request by GP-Dan-Tovbein**
Ref: https://jira.greenpeace.org/browse/PLANET-7549

# Description
Include all related files

Related PRs
- https://github.com/greenpeace/planet4-master-theme/pull/2336

## Testing
Check it out this [demo page](https://www-dev.greenpeace.org/test-venus/block-campaign-demo-page-2/) which is using the [venus](https://github.com/greenpeace/planet4-test-titan/blob/main/composer-local.json#L6-L7) dev instance for testing. 
Also disabled the P4 Gutenberg plugin from [here](https://www-dev.greenpeace.org/test-titan/wp-admin/plugins.php?plugin_status=all&paged=1&s).

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [venus](https://www-dev.greenpeace.org/test-venus) | [admin](https://www-dev.greenpeace.org/test-venus/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-venus/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-venus) | [composer-local.json](https://github.com/greenpeace/planet4-test-venus/blob/main/composer-local.json)

:watch: 2024.07.30 21:30:44

**Comment by GP-Dan-Tovbein** [comment]
> We should now be able to also remove the `gravityFormWithText` template, it's no longer used in the plugin if I'm not mistaken 🤔

The gravity form with text template is going to be removed within the [Action block pattern](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1227/files#diff-9851428c72dea5d006e44fb85e27a5bbc540d71ed1b339e04066920669125409) since it also requiring it.

**Comment by GP-Dan-Tovbein** [comment]
@mleray I think we should wait to merge this PR and the proceed to remove linked files within the removal of the [Action pattern block PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1227)

**Comment by mleray** [comment]
> @mleray I think we should wait to merge this PR and the proceed to remove linked files within the removal of the [Action pattern block PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1227)

@dantovbein you're right, sorry I didn't see that it was still used there!

**Review by mleray — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
