### PR TITLE
PLANET 4346 : Remove Conver blocks link from admin menu. Add menu ent…

### PR DESCRIPTION
**Pull request by galousis**
…ry Admin > Blocks > Reusable Blocks.

[Ref](https://jira.greenpeace.org/browse/PLANET-4346)

Part one resolved 2 out of  4 bullets

### CODE REVIEW

**Comment by galousis** [comment]
On these 2 bullets from the ticket [Ref](https://jira.greenpeace.org/browse/PLANET-4346)

- Display "Reusable block" menu when adding a block in a page/post 

- Display option to "Make block Reusable" when clicking on three dots when editing block 

after investigating i found out that in Gutenberg they did 
Hide 'Add to Reusable Blocks' button when **'core/block'** is disabled
Ref https://github.com/WordPress/gutenberg/pull/10493
https://github.com/WordPress/gutenberg/commit/c5e6adc0185c0ccbda8b644165e644be30c1ae92

In Gutenberg GP plugin the allowed_block_types filter was loading several block types except  **'core/block'**

**Comment by comzeradd** [comment]
Can you amend the commit message a bit to be smaller and more readable?

Something like: `PLANET-4346 Enable Reusable blocks, Hide Convert blocks`

**Comment by galousis** [comment]
@comzeradd done

**Comment by comzeradd** [comment]
Looks great :100:

**Pull request merged**
