### PR TITLE
PLANET-5419 Add Playwright test for Articles block

### PR DESCRIPTION
**Pull request by mleray**
### Description

See [PLANET-5419](https://jira.greenpeace.org/browse/PLANET-5419)
This is to increase our test coverage

### Description

On local, you can check the test either using the VSCode extension, or via command line by running `npx playwright test tests/e2e/articles.spec.js`

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [iocaste](https://www-dev.greenpeace.org/test-iocaste) | [admin](https://www-dev.greenpeace.org/test-iocaste/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-iocaste/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-iocaste) | [composer-local.json](https://github.com/greenpeace/planet4-test-iocaste/blob/main/composer-local.json)

:watch: 2023.07.05 08:47:54

**Review by GP-Dan-Tovbein — COMMENTED** [review]
I've tested locally by using the Playwright VS extension and the spec stopped here
```sh
      28 |   // Change amount of articles from 3 to 4.
    > 29 |   await page.getByLabel('Articles count').fill('4');
```

Any idea?

**Comment by mleray** [comment]
> I've tested locally by using the Playwright VS extension and the spec stopped here
> 
> ```shell
>       28 |   // Change amount of articles from 3 to 4.
>     > 29 |   await page.getByLabel('Articles count').fill('4');
> ```
> 
> Any idea?

I don't have that problem 🤔 Do you have any screenshots?

**Comment by lithrel** [comment]
> Any idea?

Do you see the `Articles count` string on your instance ? maybe you activated a different language ?
Works for me :+1:

**Review by lithrel — APPROVED** [review]
:+1:

**Pull request merged**
